### ISSUE TITLE
Update Charter

### ISSUE THREAD

**Issue by bensternthal** [chipsalliance/tsc#145]
- [x] Receive clean charter from legal
- [x] Update charter on [website] https://github.com/chipsalliance/chips-alliance-website/pull/105
- [x] Update charter on google drive
- [x] Update redirect https://participation-agreement.chipsalliance.org/

**Comment by bensternthal** [comment]
waiting on clean charter from legal

**Comment by bensternthal** [comment]
New link is https://www.chipsalliance.org/images/about/Chips_Alliance_Funding_Charter_v10.pdf
