### ISSUE TITLE
Platinum Appointments To TAC

### ISSUE THREAD

**Issue by bensternthal** [chipsalliance/tsc#147]
This issue tracks Platinum members appointing representatives to the TAC.

- [x] Post updated [bylaws](https://mail.google.com/mail/u/0/#inbox/FMfcgzGwJSDbjXVkMPqbnMDnQMzdQhJF?projector=1)
- [x]  [Email](https://docs.google.com/document/d/1WJZmMx3jeQTCn7ZXI8ok-ZSi2PS3kGriIEUhhYFr_tE/edit#heading=h.jn7cp7dvblob) to platinum members on Jan 2 deadline of Jan 12th
- [x] Add reps to mailing list, meetings etc
