### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by bensternthal** [chipsalliance/tsc#151]
Depending on what projects the TAC decides should be projects we may have onboarding tasks to complete. We will likely create issues for each project. The likely tasks that would need to be included are:

- [ ] Creation of project in LFX
- [ ] Submission of project to formation team
- [ ] Creation and approval of charter
- [ ] Creation and approval of participation agreement
- [ ] Creation of series agreement
- [ ] Updating the website and github repos

**Comment by bensternthal** [comment]
Closing this as issues will be created for each project.
